# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='question_text',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
